version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: github.com/franciscopessoa/books-api-db
    container_name: books-api-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/books-api-db
    volumes:
      - books-api-db:/var/lib/postgresql/data

volumes:
  books-api-db: